# Generated by Django 4.1.4 on 2022-12-15 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("store", "0002_checkoutaddress_payment_option"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkoutaddress",
            name="zip",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.CreateModel(
            name="CreateComposition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zip", models.CharField(default="", max_length=10)),
                ("color", models.CharField(default="", max_length=20)),
                ("fruit", models.BooleanField(default=False)),
                ("candies", models.BooleanField(default=False)),
                ("vegitables", models.BooleanField(default=False)),
                ("cheese", models.BooleanField(default=False)),
                ("sausages", models.BooleanField(default=False)),
                ("alcohol", models.BooleanField(default=False)),
                ("snacks", models.BooleanField(default=False)),
                ("cones", models.BooleanField(default=False)),
                ("needles", models.BooleanField(default=False)),
                ("christmas_decorations", models.BooleanField(default=False)),
                ("joke_decorations", models.BooleanField(default=False)),
                ("handmade_decorations", models.BooleanField(default=False)),
                ("message", models.TextField(default="", max_length=2000)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
