# Generated by Django 4.1.4 on 2022-12-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_alter_checkoutaddress_zip_createcomposition"),
    ]

    operations = [
        migrations.AddField(
            model_name="createcomposition",
            name="fake_flowers",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="createcomposition",
            name="flowers",
            field=models.BooleanField(default=False),
        ),
    ]
