# Generated by Django 4.1.4 on 2022-12-15 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_createcomposition_fake_flowers_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="createcomposition",
            name="user",
        ),
    ]
