# Generated by Django 4.1.4 on 2022-12-14 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_alter_checkoutaddress_phone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="checkoutaddress",
            name="phone",
        ),
    ]
