# Generated by Django 4.1.4 on 2022-12-14 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_remove_checkoutaddress_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkoutaddress",
            name="phone",
            field=models.CharField(default=0, max_length=10),
        ),
    ]
