# Generated by Django 4.1.4 on 2022-12-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_remove_createcomposition_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="createcomposition",
            name="name",
            field=models.CharField(default="", max_length=20),
        ),
    ]
