# Generated by Django 4.1.4 on 2022-12-14 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_checkoutaddress_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkoutaddress",
            name="phone",
            field=models.IntegerField(default=0),
        ),
    ]
