# Generated by Django 4.1.4 on 2022-12-15 17:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_createcomposition_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="createcomposition",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="createcomposition",
            name="alcohol",
            field=models.BooleanField(default=False, verbose_name="Алкоголь"),
        ),
        migrations.AlterField(
            model_name="createcomposition",
            name="candies",
            field=models.BooleanField(default=False, verbose_name="Цукерки"),
        ),
        migrations.AlterField(
            model_name="createcomposition",
            name="cheese",
            field=models.BooleanField(default=False, verbose_name="Сири"),
        ),
        migrations.AlterField(
            model_name="createcomposition",
            name="christmas_decorations",
            field=models.BooleanField(default=False, verbose_name="Новорічні прикраси"),
        ),
        migrations.AlterField(
            model_name="createcomposition",
            name="color",
            field=models.CharField(
                default="", max_length=20, verbose_name="Кольорова гамма"
            ),
        ),
        migrations.AlterField(
            model_name="createcomposition",
            name="cones",
            field=models.BooleanField(default=False, verbose_name="Шишки"),
        ),
        migrations.AlterField(
            model_name="createcomposition",
            name="fake_flowers",
            field=models.BooleanField(default=False, verbose_name="Штучні квіти"),
        ),
        migrations.AlterField(
            model_name="createcomposition",
            name="flowers",
            field=models.BooleanField(
                default=False, verbose_name="Живі квіти або листя"
            ),
        ),
        migrations.AlterField(
            model_name="createcomposition",
            name="fruit",
            field=models.BooleanField(default=False, verbose_name="Фрукти"),
        ),
        migrations.AlterField(
            model_name="createcomposition",
            name="handmade_decorations",
            field=models.BooleanField(
                default=False, verbose_name="Прикраси ручної роботи"
            ),
        ),
        migrations.AlterField(
            model_name="createcomposition",
            name="joke_decorations",
            field=models.BooleanField(default=False, verbose_name="Штучні прикраси"),
        ),
        migrations.AlterField(
            model_name="createcomposition",
            name="message",
            field=models.TextField(
                default="", max_length=2000, verbose_name="Інші побажання"
            ),
        ),
        migrations.AlterField(
            model_name="createcomposition",
            name="name",
            field=models.CharField(default="", max_length=20, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name="createcomposition",
            name="needles",
            field=models.BooleanField(default=False, verbose_name="Хвоя"),
        ),
        migrations.AlterField(
            model_name="createcomposition",
            name="sausages",
            field=models.BooleanField(default=False, verbose_name="Ковбаси"),
        ),
        migrations.AlterField(
            model_name="createcomposition",
            name="snacks",
            field=models.BooleanField(default=False, verbose_name="Снеки"),
        ),
        migrations.AlterField(
            model_name="createcomposition",
            name="vegitables",
            field=models.BooleanField(default=False, verbose_name="Овочі"),
        ),
        migrations.AlterField(
            model_name="createcomposition",
            name="zip",
            field=models.CharField(default="", max_length=10, verbose_name="+380"),
        ),
    ]
