# Generated by Django 4.1.4 on 2022-12-14 00:55

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_alter_checkoutaddress_phone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="checkoutaddress",
            name="phone",
        ),
        migrations.AddField(
            model_name="checkoutaddress",
            name="apartment_address",
            field=models.CharField(default="UA", max_length=100),
        ),
        migrations.AddField(
            model_name="checkoutaddress",
            name="country",
            field=django_countries.fields.CountryField(default="Ukraine", max_length=2),
        ),
        migrations.AddField(
            model_name="checkoutaddress",
            name="street_address",
            field=models.CharField(default="UA", max_length=100),
        ),
        migrations.AddField(
            model_name="checkoutaddress",
            name="zip",
            field=models.CharField(default="44000", max_length=100),
        ),
    ]
