# Generated by Django 4.1.4 on 2022-12-17 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_createcomposition_created_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="createcomposition",
            name="zip",
            field=models.CharField(default="", max_length=10, verbose_name="Телефон"),
        ),
    ]
