# Generated by Django 4.1.2 on 2022-12-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="posy",
            name="category",
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name="posy",
            name="description",
            field=models.CharField(max_length=5000),
        ),
        migrations.CreateModel(
            name="Categories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cat", models.ManyToManyField(to="posy.posy")),
            ],
        ),
    ]
