# Generated by Django 4.1.4 on 2022-12-15 21:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("posy", "0002_callback"),
    ]

    operations = [
        migrations.AddField(
            model_name="callback",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
