# Generated by Django 4.1.2 on 2022-12-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posy", "0002_posy_category_alter_posy_description_categories"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="categories",
            name="cat",
        ),
        migrations.RemoveField(
            model_name="posy",
            name="category",
        ),
        migrations.AddField(
            model_name="categories",
            name="category",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="posy",
            name="cat",
            field=models.ManyToManyField(to="posy.categories"),
        ),
        migrations.AlterField(
            model_name="posy",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images"),
        ),
    ]
