# Generated by Django 3.0.14 on 2022-12-07 16:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posy', '0003_remove_categories_cat_remove_posy_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='posy',
            name='cat',
        ),
        migrations.AddField(
            model_name='posy',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='posy.Categories'),
        ),
        migrations.AddField(
            model_name='posy',
            name='inventory',
            field=models.TextField(default='inventory', max_length=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categories',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='categories',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='posy',
            name='description',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='posy',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='posy',
            name='image',
            field=models.ImageField(blank=True, default='images/no_image.png', null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='posy',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='posy',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('address', models.CharField(blank=True, default='', max_length=100)),
                ('phone', models.CharField(blank=True, default='', max_length=10)),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('status', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posy.Client')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posy.Posy')),
            ],
        ),
    ]
