# Generated by Django 3.0.14 on 2022-12-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posy', '0004_auto_20221207_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posy',
            name='inventory',
            field=models.TextField(default='', max_length=2000),
        ),
    ]
