# Generated by Django 3.0.14 on 2022-12-07 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posy', '0005_auto_20221207_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posy',
            name='inventory',
        ),
    ]
