# Generated by Django 3.0.14 on 2022-12-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posy', '0006_remove_posy_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posy',
            name='category',
        ),
        migrations.AddField(
            model_name='posy',
            name='category',
            field=models.ManyToManyField(to='posy.Categories'),
        ),
    ]
