# Generated by Django 4.1.4 on 2022-12-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posy", "0008_alter_categories_id_alter_client_id_alter_order_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("sender", models.EmailField(max_length=254)),
                ("phone", models.IntegerField()),
                ("message", models.TextField(max_length=2000)),
            ],
        ),
        migrations.AddField(
            model_name="posy",
            name="inventory",
            field=models.TextField(blank=True, default="", max_length=2000, null=True),
        ),
    ]
