# Generated by Django 4.1.4 on 2022-12-10 09:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posy", "0009_feedback_posy_inventory"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="daytime",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 10, 11, 37, 7, 278978),
                verbose_name="Time published: ",
            ),
        ),
    ]
