# Generated by Django 4.1.4 on 2022-12-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posy", "0010_feedback_daytime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="daytime",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Time published: "
            ),
        ),
    ]
