# Generated by Django 4.1.4 on 2022-12-10 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posy", "0011_alter_feedback_daytime"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="client",
        ),
        migrations.RemoveField(
            model_name="order",
            name="product",
        ),
        migrations.DeleteModel(
            name="Client",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
    ]
