# Generated by Django 4.1.4 on 2022-12-12 10:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posy", "0012_remove_order_client_remove_order_product_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=50)),
                (
                    "inventory",
                    models.TextField(
                        blank=True, default="", max_length=2000, null=True
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="images/no_image.png",
                        null=True,
                        upload_to="images",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="posy",
            name="category",
        ),
    ]
