# Generated by Django 4.1.4 on 2022-12-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopping_cart", "0002_alter_useritem_product"),
        ("posy", "0013_product_remove_posy_category"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Posy",
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ManyToManyField(to="posy.categories"),
        ),
    ]
