# Generated by Django 4.1.4 on 2022-12-12 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("posy", "0013_product_remove_posy_category"),
        ("shopping_cart", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useritem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="posy.product"
            ),
        ),
    ]
