# Generated by Django 4.1.4 on 2022-12-13 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shopping_cart", "0003_order"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Order",
        ),
    ]
